const_value = 1

	const MASTER_BALL   ; $01
	const ULTRA_BALL    ; $02
	const GREAT_BALL    ; $03
	const POKE_BALL     ; $04
	const TOWN_MAP      ; $05
	const BICYCLE       ; $06
	const SURFBOARD     ; $07 buggy?
	const SAFARI_BALL   ; $08
	const POKEDEX       ; $09
	const MOON_STONE    ; $0A
	const ANTIDOTE      ; $0B
	const BURN_HEAL     ; $0C
	const ICE_HEAL      ; $0D
	const AWAKENING     ; $0E
	const PARLYZ_HEAL   ; $0F
	const FULL_RESTORE  ; $10
	const MAX_POTION    ; $11
	const HYPER_POTION  ; $12
	const SUPER_POTION  ; $13
	const POTION        ; $14
	const BOULDERBADGE  ; $15
	const CASCADEBADGE  ; $16
SAFARI_BAIT           EQU $15 ; overload
SAFARI_ROCK           EQU $16 ; overload
	const THUNDERBADGE  ; $17
	const RAINBOWBADGE  ; $18
	const SOULBADGE     ; $19
	const MARSHBADGE    ; $1A
	const VOLCANOBADGE  ; $1B
	const EARTHBADGE    ; $1C
	const ESCAPE_ROPE   ; $1D
	const REPEL         ; $1E
	const OLD_AMBER     ; $1F
	const FIRE_STONE    ; $20
	const THUNDER_STONE ; $21
	const WATER_STONE   ; $22
	const HP_UP         ; $23
	const PROTEIN       ; $24
	const IRON          ; $25
	const CARBOS        ; $26
	const CALCIUM       ; $27
	const RARE_CANDY    ; $28
	const DOME_FOSSIL   ; $29
	const HELIX_FOSSIL  ; $2A
	const SECRET_KEY    ; $2B
	const UNUSED_ITEM   ; $2C "?????"
	const BIKE_VOUCHER  ; $2D
	const X_ACCURACY    ; $2E
	const LEAF_STONE    ; $2F
	const CARD_KEY      ; $30
	const NUGGET        ; $31
	const PP_UP_2       ; $32
	const POKE_DOLL     ; $33
	const FULL_HEAL     ; $34
	const REVIVE        ; $35
	const MAX_REVIVE    ; $36
	const GUARD_SPEC_   ; $37
	const SUPER_REPEL   ; $38
	const MAX_REPEL     ; $39
	const DIRE_HIT      ; $3A
	const COIN          ; $3B
	const FRESH_WATER   ; $3C
	const SODA_POP      ; $3D
	const LEMONADE      ; $3E
	const S_S__TICKET   ; $3F
	const GOLD_TEETH    ; $40
	const X_ATTACK      ; $41
	const X_DEFEND      ; $42
	const X_SPEED       ; $43
	const X_SPECIAL     ; $44
	const COIN_CASE     ; $45
	const OAKS_PARCEL   ; $46
	const ITEMFINDER    ; $47
	const SILPH_SCOPE   ; $48
	const POKE_FLUTE    ; $49
	const LIFT_KEY      ; $4A
	const EXP__ALL      ; $4B
	const OLD_ROD       ; $4C
	const GOOD_ROD      ; $4D
	const SUPER_ROD     ; $4E
	const PP_UP         ; $4F
	const ETHER         ; $50
	const MAX_ETHER     ; $51
	const ELIXER        ; $52
	const MAX_ELIXER    ; $53
	const FLOOR_B2F     ; $54
	const FLOOR_B1F     ; $55
	const FLOOR_1F      ; $56
	const FLOOR_2F      ; $57
	const FLOOR_3F      ; $58
	const FLOOR_4F      ; $59
	const FLOOR_5F      ; $5A
	const FLOOR_6F      ; $5B
	const FLOOR_7F      ; $5C
	const FLOOR_8F      ; $5D
	const FLOOR_9F      ; $5E
	const FLOOR_10F     ; $5F
	const FLOOR_11F     ; $60
	const FLOOR_B4F     ; $61

const_value = $92

	const HM_01         ; $92
	const HM_02         ; $93
	const HM_03         ; $94
	const HM_04         ; $95
	const HM_05         ; $96
	const TM_01         ; $97
	const TM_02         ; $98
	const TM_03         ; $99
	const TM_04         ; $9A
	const TM_05         ; $9B
	const TM_06         ; $9C
	const TM_07         ; $9D
	const TM_08         ; $9E
	const TM_09         ; $9F
	const TM_10         ; $A0
	const TM_11         ; $A1
	const TM_12         ; $A2
	const TM_13         ; $A3
	const TM_14         ; $A4
	const TM_15         ; $A5
	const TM_16         ; $A6
	const TM_17         ; $A7
	const TM_18         ; $A8
	const TM_19         ; $A9
	const TM_20         ; $AA
	const TM_21         ; $AB
	const TM_22         ; $AC
	const TM_23         ; $AD
	const TM_24         ; $AE
	const TM_25         ; $AF
	const TM_26         ; $B0
	const TM_27         ; $B1
	const TM_28         ; $B2
	const TM_29         ; $B3
	const TM_30         ; $B4
	const TM_31         ; $B5
	const TM_32         ; $B6
	const TM_33         ; $B7
	const TM_34         ; $B8
	const TM_35         ; $B9
	const TM_36         ; $BA
	const TM_37         ; $BB
	const TM_38         ; $BC
	const TM_39         ; $BD
	const TM_40         ; $BE
	const TM_41         ; $BF
	const TM_42         ; $C0
	const TM_43         ; $C1
	const TM_44         ; $C2
	const TM_45         ; $C3
	const TM_46         ; $C4
	const TM_47         ; $C5
	const TM_48         ; $C6
	const TM_49         ; $C7
	const TM_50         ; $C8
	const TM_51         ; $C9
	const TM_52         ; $CA
	const TM_53         ; $CB
	const TM_54         ; $CC
	const TM_55         ; $CD
	const TM_56         ; $CE
	const TM_57         ; $CF
	const TM_58         ; $D0
	const TM_59         ; $D1
	const TM_60         ; $D2
	const TM_61         ; $D3
	const TM_62         ; $D4
	const TM_63         ; $D5
	const TM_64         ; $D6
